# Generated by Django 5.2.1 on 2025-05-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
