# Generated by Django 5.2.1 on 2025-05-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackbatch',
            name='avg_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackbatch',
            name='keyword_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
